// client/react-full/src/ProductList.js
import './ProductList.css';
import { useEffect, useState } from 'react';
import { ProductCard } from './ProductCard';

export function ProductList({ onProductSelected }) {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    fetchProducts().then(setProducts);
  }, []);

  return (
    <div className="product-list">
      <h2>Products</h2>
      <ul>
        {products.map((product) => (
          <li key={product.id}>
            <ProductCard
              product={product}
              onProductSelected={() => onProductSelected(product)}
            ></ProductCard>
          </li>
        ))}
      </ul>
    </div>
  );
}

function fetchProducts() {
  return fetch('http://localhost:3000/products').then((res) => res.json());
}

// client/vanilla-with-web-components/components/product-list.js
import './product-card.js';

export class ProductList extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });

    this.shadowRoot.innerHTML = `
      <link rel="stylesheet" href="./components/product-list.css">
      <h2>Products</h2>
      <ul></ul>
    `;
  }

  async connectedCallback() {
    this.products = await this.#fetchProducts();
    this.#update();
  }

  #update() {
    const $products = this.products.map((product) => {
      const $card = document.createElement('isy-product-card');
      $card.data = { product };
      return $card;
    });
    this.shadowRoot.querySelector('ul').replaceChildren(...$products);
  }

  async #fetchProducts() {
    const res = await fetch('http://localhost:3000/products');
    return res.json();
  }
}

customElements.define('isy-product-list', ProductList);
