// client/vanilla-with-web-components/components/cart.js
import './cart-item.js';

class Cart extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });

    this.products = new Map();

    this.shadowRoot.innerHTML = `
      <link rel="stylesheet" href="./components/cart.css">
      <h2>Cart</h2>
      <ul></ul>
    `;
  }

  addProduct(product) {
    if (!this.products.has(product.id)) {
      this.products.set(product.id, {
        quantity: 0,
        product,
      });
    }
    this.products.get(product.id).quantity++;

    this.#update();
  }

  #onQuantityChange(product, quantity) {
    if (quantity <= 0) {
      this.products.delete(product.id);
    } else {
      this.products.get(product.id).quantity = quantity;
    }
  }

  #update() {
    const $products = Array.from(this.products.values()).map(
      ({ product, quantity }) => {
        const $card = document.createElement('isy-cart-item');

        $card.data = { product, quantity };
        $card.addEventListener('change-cart-product-quantiy', (e) =>
          this.#onQuantityChange(product, e.detail)
        );

        return $card;
      }
    );
    this.shadowRoot.querySelector('ul').replaceChildren(...$products);
  }
}

customElements.define('isy-cart', Cart);

// client/react-full/src/Cart.js
import './Cart.css';
import { Component } from 'react';
import { CartItem } from './CartItem';

export class Cart extends Component {
  constructor(props) {
    super(props);
    this.state = {
      cartEntries: new Map(),
    };
  }

  addProduct(product) {
    if (!this.state.cartEntries.has(product.id)) {
      this.state.cartEntries.set(product.id, {
        quantity: 0,
        product,
      });
    }
    this.state.cartEntries.get(product.id).quantity++;

    this.setState(this.state);
  }

  #onQuantityChange = (productId, change) => {
    const cartEntry = this.state.cartEntries.get(productId);
    cartEntry.quantity += change;
    this.setState(this.state);
  };

  render() {
    return (
      <div className="cart">
        <h2>Cart</h2>
        <ul>
          {Array.from(this.state.cartEntries.values())
            .filter(({ quantity }) => quantity > 0)
            .map((ce) => (
              <li key={ce.product.id}>
                <CartItem
                  cartEntry={ce}
                  onQuantityChange={this.#onQuantityChange}
                />
              </li>
            ))}
        </ul>
      </div>
    );
  }
}
